# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import tkinter
from tkinter import *
from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc
from PyQt5.QtWidgets import QTableWidgetItem


class Ui_Dash(object):

    def his(self):
        from History import Ui_MainWindow
        self.Window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.Window)
        self.Window.show()
        roo = tkinter.Tk()
        btn = Button(roo, text='Get Data', command=self.chi)
        btn.pack(pady=10)
        btn1 = Button(roo, text='Close', command=roo.destroy)
        btn1.pack(pady=20)
        roo.mainloop()

    def chi(self):
        us = self.label.text()
        self.ui.label_2.setText(us)

    def po(self):
        from Profile import Ui_MainWindow
        self.Window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.Window)
        self.Window.show()
        roo = tkinter.Tk()
        btn = Button(roo, text='Get Data', command=self.cpo)
        btn.pack(pady=10)
        btn1 = Button(roo, text='Close', command=roo.destroy)
        btn1.pack(pady=20)
        roo.mainloop()

    def cpo(self):
        us = self.label.text()
        self.ui.label_5.setText(us)

    def me(self):
        from MyExp import Ui_Mye
        self.Windowsme = QtWidgets.QMainWindow()
        self.ui = Ui_Mye()
        self.ui.setupUi(self.Windowsme)
        self.Windowsme.show()
        roo = tkinter.Tk()
        btn = Button(roo, text='Get Data', command=self.cme)
        btn.pack(pady=10)
        btn1 = Button(roo, text='Close', command=roo.destroy)
        btn1.pack(pady=20)
        roo.mainloop()

    def logout(self):
        from Log import Ui_Log
        self.Window = QtWidgets.QMainWindow()
        self.ui = Ui_Log()
        self.ui.setupUi(self.Window)
        MainWindow1.close()
        self.Window.show()

    def cme(self):
        us = self.label.text()
        self.ui.label_7.setText(us)

    def table(self):
        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="H@rSHiTR24",
                database="expense"
            )
            myc = mydb.cursor()
            qr = "select * from college"
            myc.execute(qr)
            result = myc.fetchmany(3)

            self.tableWidget.setRowCount(0)

            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)

                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number,
                                             column_number, QTableWidgetItem(str(data)))
        except mc.Error as e:
            print("Error occured")

    def setupUi(self, MainWindow):

        MainWindow.setObjectName("Ui_Dash")
        MainWindow.resize(1366, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1366, 800))
        self.frame.setStyleSheet("\n"
                                 "background-color: rgb(9, 21, 30);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 250, 800))
        self.frame_2.setStyleSheet("background-color: rgb(21, 46, 67);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(0, 2, 250, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(0, 80, 250, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);\n"
                                      "background-color: rgb(21, 41, 67, 100);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 220, 250, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("color: rgb(255, 255, 255);\n"
                                        "background-color: rgb(21, 41, 67, 100);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.me)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 290, 250, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("color: rgb(255, 255, 255);\n"
                                        "background-color: rgb(21, 41, 67, 100);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.graph)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 360, 250, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("color: rgb(255, 255, 255);\n"
                                        "background-color: rgb(21, 41, 67, 100);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.his)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_6.setGeometry(QtCore.QRect(0, 430, 250, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("color: rgb(255, 255, 255);\n"
                                        "background-color: rgb(21, 41, 67, 100);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.clicked.connect(self.logout)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 150, 250, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("color: rgb(255, 255, 255);\n"
                                        "background-color: rgb(21, 41, 67, 100);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.clicked.connect(self.po)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(250, 0, 1121, 200))
        self.frame_3.setStyleSheet("background-color: rgb(67, 167, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(50, 0, 661, 201))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(310, 240, 441, 231))
        self.frame_4.setStyleSheet("\n"
                                   "background-color: rgb(81, 181, 50);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setGeometry(QtCore.QRect(50, 30, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setGeometry(QtCore.QRect(50, 100, 261, 100))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.label_5.setObjectName("label_5")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setGeometry(QtCore.QRect(850, 240, 441, 231))
        self.frame_5.setStyleSheet("\n"
                                   "background-color: rgb(208, 0, 0);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        self.label_4.setGeometry(QtCore.QRect(50, 30, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        self.label_6.setGeometry(QtCore.QRect(50, 100, 261, 100))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.label_6.setObjectName("label_6")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(850, 660, 150, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(67, 167, 255);\n"
                                        "")
        self.pushButton_2.setObjectName("pushButton_2")

        self.pushButton_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8.setGeometry(QtCore.QRect(630, 660, 150, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("background-color: rgb(67, 167, 255);\n"
                                        "")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_8.clicked.connect(self.tab)

        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setGeometry(QtCore.QRect(610, 500, 400, 150))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):

        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", ""))
        self.pushButton.setText(_translate("MainWindow", "Home"))
        self.pushButton_3.setText(_translate("MainWindow", "My Expense"))
        self.pushButton_4.setText(_translate("MainWindow", "Tabular Form"))
        self.pushButton_5.setText(_translate("MainWindow", "History"))
        self.pushButton_6.setText(_translate("MainWindow", "Logout"))
        self.pushButton_7.setText(_translate("MainWindow", "Profile"))
        self.label_3.setText(_translate("MainWindow", ""))
        self.label_2.setText(_translate("MainWindow", "Credited"))
        self.label_5.setText(_translate("MainWindow", ""))
        self.label_4.setText(_translate("MainWindow", "Debited"))
        self.label_6.setText(_translate("MainWindow", ""))
        self.pushButton_2.setText(_translate("MainWindow", "View More"))
        self.pushButton_8.setText(_translate("MainWindow", "Load"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Mode"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Type"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Amount"))

    def tab(self):

        us = self.label.text()
        mydb = mc.connect(
            host="localhost",
            user="root",
            password="H@rSHiTR24",
            database="expense"
        )
        myc = mydb.cursor()
        rec = myc.execute("select Account_no from User where Username = '" + us + "'")
        rec = myc.fetchmany(1)
        for row in rec:
            an = row[0]

        no = str(an)

        rs = myc.execute("select * from User where Account_No = '" + no + "'")
        rec = myc.fetchmany(1)
        for row in rec:
            nam = row[0]
            unam = row[1]
            em = row[2]
            mob = row[3]
            pas = row[4]
            acc = row[5]

        self.label_3.setText(nam)

        tp = "Credit"
        sq = "select sum(Amount) from Transaction where Account_no = '" + acc + "' and Type = '" + tp + "'"
        myc.execute(sq)
        rec1 = myc.fetchall()
        for row in rec1:
            cr = row[0]

        cre = str(cr)
        self.label_5.setText(cre)

        tp1 = "Debit"
        sq1 = "select sum(Amount) from Transaction where Account_no = '" + acc + "' and Type = '" + tp1 + "'"
        myc.execute(sq1)
        rec2 = myc.fetchall()
        for row in rec2:
            cr1 = row[0]

        cre1 = str(cr1)
        self.label_6.setText(cre1)

        try:
            qr = "select Date, Type, Transaction_Method, Amount from Transaction where Account_No = '" + no + "'"
            myc.execute(qr)
            result = myc.fetchmany(3)

            self.tableWidget.setRowCount(0)

            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)

                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number,
                                             column_number, QTableWidgetItem(str(data)))


        except mc.Error as e:
            print("Error occured1")

    def graph(self):
        import matplotlib.pyplot as plt
        import numpy as np

        us = self.label.text()
        mydb = mc.connect(
            host="localhost",
            user="root",
            password="H@rSHiTR24",
            database="expense"
        )
        myc = mydb.cursor()
        rec = myc.execute("select Account_no from User where Username = '" + us + "'")
        rec = myc.fetchmany(1)
        for row in rec:
            an = row[0]

        acc = str(an)

        myc = mydb.cursor()
        tp = "Credit"
        sq = "select sum(Amount) from Transaction where Account_no = '" + acc + "' and Type = '" + tp + "'"
        myc.execute(sq)
        rec1 = myc.fetchall()
        for row in rec1:
            cr = row[0]

        tp1 = "Debit"
        sq1 = "select sum(Amount) from Transaction where Account_no = '" + acc + "' and Type = '" + tp1 + "'"
        myc.execute(sq1)
        rec2 = myc.fetchall()
        for row in rec2:
            cr1 = row[0]

        cre = int(cr)
        deb = int(cr1)

        arr = [cre, deb]
        myl = ["Credit", "Debit"]
        plt.pie(arr, labels=myl)
        plt.show()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow1 = QtWidgets.QMainWindow()
    ui = Ui_Dash()
    ui.setupUi(MainWindow1)
    MainWindow1.show()
    sys.exit(app.exec_())
