# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc


class Ui_MainWindow(object):

    def log(self):
        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="H@rSHiTR24",
                database="expense"
            )
            nam = self.lineEdit.text()
            una = self.lineEdit_4.text()
            em = self.lineEdit_2.text()
            mobi = self.lineEdit_3.text()
            pas = self.lineEdit_12.text()
            acc = self.lineEdit_5.text()

            myc = mydb.cursor()
            sql = "insert into User (Name, Username,Email, Mobile, Password) values (%s,%s,%s,%s,%s)"
            val = (nam, una, em, mobi, pas)
            myc.execute(sql, val)
            mydb.commit()

        except mc.Error as e:
            print("Error occured")

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(625, 625)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 856, 800))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../IMG/ezgif.com-gif-maker.jpg"))
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(850, 0, 521, 811))
        self.frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.raise_()
        self.label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
